### ISSUE TITLE
Allow the ability to set the command in settings

### ISSUE THREAD

**Issue by boek** [craigsheen/atom-guard-rspec#8]
I run guard through bundler. So being able to change the command from `guard` to `bundle exec guard` would be awesome!

If this is something you would like to have in this plugin I have another PR ready

**Comment by craigsheen** [comment]
This would be great.

**Comment by boek** [comment]
Whelp, as I referenced on the code in #7, it seems that I accidentally pushed my changes to that branch before you merged it. So.. It's in now!

**Comment by craigsheen** [comment]
Looked fine anyway 👍
